// Declarative index of existing owners. Discovery is evidence of a definition, never a passing test or live outcome.
export const surfaces = [
	"agent-loop",
	"prompts-instructions",
	"model-provider",
	"context-construction",
	"memory-persistence",
	"search-grep",
	"lsp",
	"file-reads",
	"edits",
	"shell",
	"test-execution",
	"git",
	"tool-routing",
	"subagents",
	"permissions",
	"retry-recovery",
	"compaction",
	"ui-extension",
]
export const columns = ["mechanical", "component", "e2e", "regression", "robustness", "security", "performance", "live"]
export const layers = [
	"mechanical",
	"unit",
	"contract",
	"independent-task-outcomes",
	"regression",
	"capability",
	"trajectory",
	"robustness",
	"security",
	"performance",
	"variance",
	"replay",
	"canary",
	"ab",
	"monitoring",
].map((name, id) => ({ id, name }))

const component = (id, surface, source, tests, extra = {}) => ({
	id,
	surfaces: [surface],
	columns: ["component", "regression"],
	layers: [1, 4],
	source: [source],
	tests,
	lanes: ["focused", "unit"],
	kind: "component-test",
	...extra,
})
const host = (id, surface, tests, extra = {}) => ({
	id,
	surfaces: [surface],
	columns: ["e2e"],
	layers: [2],
	source: ["apps/vscode-e2e/src/runTest.ts"],
	tests: tests.map((file) => `apps/vscode-e2e/src/suite/${file}.ts`),
	lanes: ["host", "confidence"],
	kind: "scripted-host-test",
	...extra,
})

export const evidenceInventory = [
	{
		id: "workspace-mechanics",
		surfaces,
		columns: ["mechanical"],
		layers: [0],
		source: [
			"package.json",
			"src/package.json",
			"turbo.json",
			".github/workflows/code-qa.yml",
			"scripts/harness/catalog.mjs",
		],
		tests: [],
		lanes: ["static"],
		kind: "mechanical-command",
		scope: "Lint and type contracts; no task outcome or runtime quality claim",
	},
	component("turn-engine", "agent-loop", "src/core/agent/AgentTurnEngine.ts", [
		"src/core/agent/__tests__/AgentTurnEngine.spec.ts",
		"src/core/agent/__tests__/AgentStepRuntime.spec.ts",
		"src/core/agent/__tests__/AgentTurnEngine.fault-contract.spec.ts",
		"src/core/agent/lifecycle/__tests__/reducer.spec.ts",
	]),
	component(
		"instructions",
		"prompts-instructions",
		"src/core/prompts/sections/custom-instructions.ts",
		[
			"src/core/prompts/__tests__/system-prompt.spec.ts",
			"src/core/prompts/__tests__/codex-runtime-instructions.spec.ts",
			"src/core/prompts/sections/__tests__/custom-instructions-discovery.spec.ts",
		],
		{ columns: ["component", "regression", "security"], layers: [1, 2, 4, 8] },
	),
	component(
		"provider-contracts",
		"model-provider",
		"src/api/providers/vscode-lm.ts",
		[
			"src/api/providers/__tests__/vscode-lm-contracts.spec.ts",
			"src/api/providers/__tests__/transport-parity.spec.ts",
			"src/api/transform/__tests__/vscode-lm-format.spec.ts",
		],
		{ layers: [1, 2, 4] },
	),
	component("step-context", "context-construction", "src/core/agent/AgentStepContextBuilder.ts", [
		"src/core/agent/__tests__/AgentStepContextBuilder.spec.ts",
		"src/core/agent/__tests__/StepContext.spec.ts",
		"src/core/agent/__tests__/SubagentContextCapture.spec.ts",
	]),
	component(
		"transcript-persistence",
		"memory-persistence",
		"src/core/task-persistence/ProviderTranscriptStore.ts",
		[
			"src/core/task-persistence/__tests__/ProviderTranscriptStore.spec.ts",
			"src/core/task-persistence/__tests__/transcriptConflict.spec.ts",
			"src/core/task-persistence/__tests__/stageThreeVerificationRecovery.integration.spec.ts",
		],
		{
			columns: ["component", "regression", "robustness"],
			layers: [1, 4, 7, 11],
			scope: "Transcript recovery/replay; no separate learned-memory quality claim",
		},
	),
	component("search", "search-grep", "src/services/ripgrep/index.ts", [
		"src/services/ripgrep/__tests__/execution.spec.ts",
		"src/core/tools/__tests__/SearchFilesTool.spec.ts",
		"src/services/search/__tests__/file-search.paths.spec.ts",
	]),
	component(
		"diagnostics-adapter",
		"lsp",
		"src/integrations/diagnostics/index.ts",
		[
			"src/integrations/diagnostics/__tests__/diagnostics.spec.ts",
			"src/core/tools/__tests__/ReadDiagnosticEvidenceTool.spec.ts",
		],
		{ scope: "VS Code diagnostics adapter; language-server protocol and real server coverage remain a gap" },
	),
	component("read-file", "file-reads", "src/core/tools/ReadFileTool.ts", [
		"src/core/tools/__tests__/readFileTool.spec.ts",
		"src/core/tools/__tests__/readFileTool.pagination.spec.ts",
	]),
	component(
		"file-mutations",
		"edits",
		"src/core/tools/ApplyPatchTool.ts",
		[
			"src/core/tools/__tests__/ApplyPatchTool.spec.ts",
			"src/core/tools/__tests__/applyPatchTool.partial.spec.ts",
			"src/core/tools/__tests__/writeToFileTool.spec.ts",
		],
		{ columns: ["component", "regression", "security"], layers: [1, 4, 8] },
	),
	component(
		"shell-process",
		"shell",
		"src/core/tools/ExecuteCommandTool.ts",
		[
			"src/core/tools/__tests__/executeCommandTool.spec.ts",
			"src/core/tools/__tests__/ParallelCommandRead.integration.spec.ts",
			"src/integrations/terminal/__tests__/ExecaTerminalProcess.settlement.spec.ts",
		],
		{ columns: ["component", "regression", "robustness"], layers: [1, 4, 7] },
	),
	component("verification", "test-execution", "src/core/agent/VerificationScope.ts", [
		"src/core/agent/__tests__/VerificationScope.spec.ts",
		"src/core/agent/__tests__/CommandOutcomeContext.spec.ts",
		"src/core/agent/__tests__/AgentControlStore.primary-verification.spec.ts",
	]),
	component(
		"git-checkpoint",
		"git",
		"src/services/checkpoints/ShadowCheckpointService.ts",
		[
			"src/services/checkpoints/__tests__/ShadowCheckpointService.spec.ts",
			"src/services/checkpoints/__tests__/checkpoint-cancellation.spec.ts",
			"packages/core/src/worktree/__tests__/managed-subagent-worktree.persistence.spec.ts",
		],
		{ columns: ["component", "regression", "robustness"], layers: [1, 4, 7] },
	),
	component(
		"tool-routing",
		"tool-routing",
		"src/core/tools/ToolRegistry.ts",
		[
			"src/core/tools/__tests__/ToolRegistry.spec.ts",
			"src/core/tools/__tests__/TaskToolSurface.spec.ts",
			"src/core/tools/__tests__/WorkflowScriptedCatalog.spec.ts",
			"src/core/tools/__tests__/nativeToolDispatchContract.spec.ts",
		],
		{ layers: [1, 2, 4] },
	),
	component(
		"managed-agents",
		"subagents",
		"src/core/agent/BoundedDelegationManager.ts",
		[
			"src/core/agent/__tests__/BoundedDelegationManager.result-contract.spec.ts",
			"src/core/agent/__tests__/BoundedDelegationManager.stop-reasons.spec.ts",
			"src/core/agent/__tests__/InternalTaskEnvelope.authority-contract.spec.ts",
		],
		{ columns: ["component", "regression", "robustness", "security"], layers: [1, 2, 4, 7, 8] },
	),
	component(
		"tool-permissions",
		"permissions",
		"src/core/agent/ToolPolicy.ts",
		[
			"src/core/agent/__tests__/ToolPolicy.spec.ts",
			"src/core/agent/__tests__/outsideWorkspaceAccess.spec.ts",
			"src/core/auto-approval/__tests__/AutoApprovalHandler.spec.ts",
		],
		{ columns: ["component", "regression", "security"], layers: [1, 4, 8] },
	),
	component(
		"persistent-evidence-redaction",
		"permissions",
		"src/core/agent/AgentTurnEventLog.ts",
		["src/core/agent/__tests__/AgentEvidence.security.spec.ts"],
		{ columns: ["component", "regression", "security"], layers: [1, 4, 8] },
	),
	component(
		"retry-recovery",
		"retry-recovery",
		"src/core/agent/AgentRetryPolicy.ts",
		[
			"src/core/agent/__tests__/AgentRetryPolicy.spec.ts",
			"src/core/task/__tests__/Task.failure-recovery.spec.ts",
			"src/core/agent/__tests__/AgentControlStore.recovery-races.spec.ts",
		],
		{ columns: ["component", "regression", "robustness"], layers: [1, 4, 7] },
	),
	component(
		"compaction",
		"compaction",
		"src/core/context-management/index.ts",
		[
			"src/core/context-management/__tests__/compaction-policy.spec.ts",
			"src/core/context-management/__tests__/recovery.spec.ts",
			"src/core/task/__tests__/Task.compaction-safety.spec.ts",
		],
		{ columns: ["component", "regression", "robustness"], layers: [1, 4, 7] },
	),
	component("webview-projection", "ui-extension", "webview-ui/src/context/ExtensionStateContext.tsx", [
		"webview-ui/src/context/__tests__/ExtensionStateContext.refresh.spec.tsx",
		"webview-ui/src/context/__tests__/followup-lifecycle-projection.spec.ts",
		"webview-ui/src/components/settings/__tests__/SettingsView.spec.tsx",
	]),
	host("host-loop", "agent-loop", ["core-loop.test", "core-loop-boundaries.test"], { layers: [2, 6] }),
	host("host-instructions", "prompts-instructions", ["instruction-discovery.acceptance.test"]),
	host("host-lm", "model-provider", ["vscode-lm-contract.test", "vscode-lm-empty-recovery.test"]),
	host("host-context", "context-construction", ["long-context-fanout.test", "proportional-context.test"]),
	host("host-storage", "memory-persistence", ["storage-recovery.test", "storage-restart.test"], {
		columns: ["e2e", "robustness"],
		layers: [2, 7, 11],
	}),
	host("host-search", "search-grep", ["tool-search.acceptance.test", "tools/search-files.test"]),
	host("host-reads", "file-reads", ["tools/read-file.test"]),
	host("host-edits", "edits", ["command-file-diff.test", "tools/apply-diff.test", "tools/write-to-file.test"]),
	host("host-shell", "shell", [
		"command-settlement.test",
		"command-path-approval.test",
		"tools/execute-command.test",
	]),
	host("host-verification", "test-execution", ["completion-idle.test", "proportional-completion.test"]),
	host("host-tool-routing", "tool-routing", ["update-plan.acceptance.test", "view-image.acceptance.test"]),
	host(
		"host-managed",
		"subagents",
		[
			"managed-agents.acceptance.test",
			"managed-agents.cancellation.acceptance.test",
			"managed-agents.budget.acceptance.test",
		],
		{ columns: ["e2e", "robustness"], layers: [2, 7] },
	),
	host("host-permissions", "permissions", ["approval-mode.test", "command-path-approval.test"], {
		columns: ["e2e", "security"],
		layers: [2, 8],
	}),
	host("host-recovery", "retry-recovery", ["nested-restart.test", "vscode-lm-empty-recovery.test"], {
		columns: ["e2e", "robustness"],
		layers: [2, 7],
	}),
	host("host-compaction", "compaction", ["compaction-acceptance.test"]),
	host("host-ui", "ui-extension", ["extension.test", "modes.test", "rendered-ui-probe.test", "history-ui.test"]),
	{
		id: "evaluator-contracts",
		surfaces: ["test-execution", "permissions", "retry-recovery", "git"],
		columns: ["component", "regression", "robustness", "security"],
		layers: [1, 2, 4, 7, 8],
		source: [
			"packages/evals/src/grading/index.ts",
			"packages/evals/src/benchmark/graderBroker.ts",
			"packages/evals/src/cli/workspaceChanges.ts",
			"scripts/harness/outcome-proof.mjs",
			"scripts/harness/matrix.mjs",
		],
		tests: [
			"packages/evals/src/grading/__tests__/failClosed.spec.ts",
			"packages/evals/src/grading/__tests__/grading.spec.ts",
			"packages/evals/src/grading/__tests__/containmentAndUsage.spec.ts",
			"packages/evals/src/benchmark/__tests__/graderBroker.spec.ts",
			"packages/evals/src/cli/__tests__/workspaceChanges.spec.ts",
			"packages/evals/src/certification/__contracts__/certification.spec.ts",
			"scripts/harness/execution-evidence.test.mjs",
			"scripts/harness/host-evidence.test.mjs",
			"scripts/harness/outcome-proof.test.mjs",
			"scripts/harness/matrix.test.mjs",
		],
		lanes: ["offline", "tooling"],
		kind: "grader-component-test",
		scope: "Grader, evidence admission and certification contracts; component checks do not establish independent agent task outcomes",
	},
	{
		id: "independent-outcome-graders",
		surfaces,
		columns: ["component"],
		layers: [3, 5],
		source: ["evals/grader-controls/smoke-v1.json", "packages/evals/src/grading/registry.ts"],
		tests: ["packages/evals/src/grading/__contracts__/localFixtures.spec.ts"],
		lanes: ["offline"],
		kind: "outcome-definition",
		scope: "Independent fixture oracles and calibration definitions; real agent task outcomes require separately bound task evidence",
		promotion: "unavailable",
	},
	{
		id: "scripted-independent-outcomes",
		surfaces: [
			"agent-loop",
			"context-construction",
			"file-reads",
			"search-grep",
			"edits",
			"shell",
			"test-execution",
			"git",
			"tool-routing",
			"ui-extension",
		],
		columns: ["e2e", "regression"],
		layers: [3, 5],
		source: [
			"apps/vscode-e2e/src/campaign/developmentSuites.ts",
			"apps/vscode-e2e/src/scenarios/workflowDriver.ts",
			"apps/vscode-e2e/src/scenarios/developmentFixture.ts",
		],
		tests: ["apps/vscode-e2e/src/suite/workflow.test.ts"],
		lanes: ["outcomes"],
		kind: "scripted-outcome-test",
		scope: "Three real-extension scripted tasks with independently checked repository outcomes; no measured live model capability",
	},
	{
		id: "trajectory-replay",
		surfaces: ["agent-loop", "memory-persistence", "subagents", "retry-recovery", "compaction"],
		columns: ["component", "regression"],
		layers: [6, 11],
		source: ["packages/evals/src/evidence/index.ts"],
		tests: [
			"packages/evals/src/evidence/__contracts__/reconstruction.spec.ts",
			"src/core/agent/lifecycle/__tests__/AgentLifecycleJournal.spec.ts",
		],
		lanes: ["offline", "focused", "unit"],
		kind: "replay-component-test",
		scope: "Evidence reconstruction and canonical lifecycle replay; no provider replay equivalence claim",
	},
	{
		id: "performance-definitions",
		surfaces: ["context-construction", "agent-loop", "memory-persistence", "search-grep", "git", "ui-extension"],
		columns: ["performance"],
		layers: [9],
		source: ["src/core/agent/benchmarks/StepContext.benchmark.ts", "scripts/evals/proportional-scope-compare.mjs"],
		tests: [
			"src/services/checkpoints/__tests__/checkpoint-performance.spec.ts",
			"src/core/task-persistence/__tests__/nor-29-benchmark.spec.ts",
			"apps/vscode-e2e/src/suite/task-navigation-latency.test.ts",
		],
		lanes: ["focused", "unit"],
		kind: "performance-definition",
		scope: "Existing measurement definitions; no comparable before/after performance receipt imported",
		promotion: "unavailable",
	},
	{
		id: "variance-ab-machinery",
		surfaces,
		columns: ["component"],
		layers: [10, 13],
		source: ["packages/evals/src/experiments/pairing.ts", "packages/evals/src/experiments/statistics.ts"],
		tests: [
			"packages/evals/src/experiments/__tests__/experiments.spec.ts",
			"packages/evals/src/experiments/__tests__/hostCampaign.spec.ts",
		],
		lanes: ["offline"],
		kind: "comparison-component-test",
		scope: "Pairing/statistical machinery; real comparable multi-sample experiments and production A/B are unavailable",
		promotion: "unavailable",
	},
	{
		id: "live-suites",
		surfaces,
		columns: ["live"],
		layers: [3, 5, 6, 10],
		source: ["apps/vscode-e2e/src/campaign/liveGate.ts", "packages/evals/src/benchmark/problemSolvingLive.ts"],
		tests: [
			"apps/vscode-e2e/src/suite/live-quality.test.ts",
			"apps/vscode-e2e/src/suite/harness-quality-live.test.ts",
			"apps/vscode-e2e/src/suite/approval-github-live.test.ts",
		],
		lanes: [],
		kind: "live-definition",
		scope: "Defined supplemental live suites; no live or production receipt imported by this offline inventory",
		promotion: "unavailable",
	},
]

export const layerGaps = {
	3: "Independent oracles exist; component/host test passes do not establish separately graded agent outcomes",
	5: "Capability fixtures exist; coverage of the full capability task bank is unavailable",
	9: "No admitted comparable before/after measurement is imported by this index",
	10: "Variance machinery exists; real repeated comparable model observations are unavailable",
	11: "Narrow transcript/reconstruction replay contracts exist; no admitted real workload/candidate shadow or replay evidence is available",
	12: "No production canary deployment or production evidence owner is configured",
	13: "Offline comparison machinery exists; no production A/B observation is available",
	14: "No production monitoring signal or service-level objective evidence is configured",
}
